apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: threatcast-zero-trust-policy
  namespace: threatcast-system
spec:
  podSelector: {}
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - from:
        - podSelector:
            matchLabels:
              app: threatcast-frontend
      ports:
        - protocol: TCP
          port: 8000
    - from:
        - podSelector:
            matchLabels:
              app: threatcast-backend
      ports:
        - protocol: TCP
          port: 5432
        - protocol: TCP
          port: 6379
        - protocol: TCP
          port: 9092
  egress:
    - to:
        - podSelector:
            matchLabels:
              app: threatcast-backend
      ports:
        - protocol: TCP
          port: 8000
